# Generated by Django 2.2.5 on 2019-09-06 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='thumbnail',
            field=models.CharField(default='Thumbnail', max_length=250),
        ),
    ]
