# Generated by Django 2.0.7 on 2019-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_lib',
            field=models.BooleanField(choices=[(True, 'IN'), (False, 'OUT')], default=True),
        ),
        migrations.AddField(
            model_name='books',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
