# Generated by Django 2.0.7 on 2019-09-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190910_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='in_lib',
            field=models.BooleanField(choices=[(True, 'IN'), (False, 'OUT')], default=True),
        ),
    ]
